#ARGS
ARG APACHE_TAG=${APACHE_TAG}
ARG HOST_SERVER_NAME=${HOST_SERVER_NAME}

FROM httpd:${APACHE_TAG}

ARG GLPIPATH=${GLPIPATH}
ARG HOST_SERVER_WEB_PORT=${HOST_SERVER_WEB_PORT}
# Environment variables
ENV GLPIPATH ${GLPIPATH}
ENV HOST_SERVER_WEB_PORT ${HOST_SERVER_WEB_PORT}
ENV HOST_SERVER_NAME ${HOST_SERVER_NAME}

# Install modules
RUN apt-get update && apt-get install -y curl nano

WORKDIR $GLPIPATH
