#!/bin/bash
if [ "$1" != "" ] && [ "$1" != "-h" ]
then
    cd $GLPIPATH
    if [ "$1" == "-i" ]; then # Instalation process
        mysql -u root -p $MYSQL_ROOT_PASSWORD -e "DROP DATABASE IF EXISTS \`$GLPI_DB_NAME_TEST\`"
        mysql -u root -p $MYSQL_ROOT_PASSWORD -e "DROP DATABASE IF EXISTS \`$GLPI_DB_NAME_UPGRADE_TEST\`"
        echo "=== Install tests ==="
        PHPSCRIPT='tools/cliinstall.php';
        if [ -f scripts/cliinstall.php ]; then
             PHPSCRIPT='scripts/cliinstall.php';
        fi

        php $PHPSCRIPT --db=$GLPI_DB_NAME_TEST --user=root --pass=$MYSQL_ROOT_PASSWORD --tests --force
        php $PHPSCRIPT --db=$GLPI_DB_NAME_UPGRADE_TEST --user=root --pass=$MYSQL_ROOT_PASSWORD --tests --force
        php plugins/$FUSIONINVENTORY_PATH/scripts/cli_install.php --tests

        mysql -u root -p$MYSQL_ROOT_PASSWORD $GLPI_DB_NAME_UPGRADE_TEST < tests/plugin_flyvemdm_empty_2.0.0-rc.1.sql
        mysql -u root -p$MYSQL_ROOT_PASSWORD $GLPI_DB_NAME_UPGRADE_TEST < tests/plugin_flyvemdm_config_2.0.0-rc.1.sql

        php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc -d plugins$FLYVEMDM_PATH/tests/suite-install
        if [ "$2" == "-eall" ]; then
            echo "=== Unit tests ==="
            php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc -d plugins$FLYVEMDM_PATH/tests/suite-unit
            echo "=== Integration tests ==="
            php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc -d plugins$FLYVEMDM_PATH/tests/suite-integration
        elif [ "$2" == "-eone" ] && [ "$3" != "" ]; then # Execution process individual
            echo "=== Unit tests / Integration test ==="
            if [ -f plugins$FLYVEMDM_PATH/$3 ]; then
                RESOURCE_TYPE="-f"
            elif [ -d plugins$FLYVEMDM_PATH/$3 ]; then
                RESOURCE_TYPE="-d"
            fi
            php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc $RESOURCE_TYPE plugins$FLYVEMDM_PATH/$3
        fi
        if [ "$4" == "-u" ]; then # Uninstalation process
            echo "=== Uninstall tests ==="
            php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc -d plugins$FLYVEMDM_PATH/tests/suite-uninstall
        fi
    elif [ "$1" == "-u" ]; then # Uninstalation process
        echo "=== Uninstall tests ==="
        php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc -d plugins$FLYVEMDM_PATH/tests/suite-uninstall
    elif [ "$1" == "-eone" ] && [ "$2" != "" ]; then # Execution process individual
        echo "=== Unit tests / Integration test ==="
        if [ -f plugins$FLYVEMDM_PATH/$2 ]; then
            RESOURCE_TYPE="-f"
        elif [ -d plugins$FLYVEMDM_PATH/$2 ]; then
            RESOURCE_TYPE="-d"
        fi
        php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc $RESOURCE_TYPE plugins$FLYVEMDM_PATH/$2
        if [ "$3" != "" ] && [ "$3" == "-u" ]; then # Uninstalation process
            echo "=== Uninstall tests ==="
            php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc -d plugins$FLYVEMDM_PATH/tests/suite-uninstall
        fi
    elif [ "$1" == "-eall" ]; then
        echo "=== Unit tests ==="
        php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc -d plugins$FLYVEMDM_PATH/tests/suite-unit
        echo "=== Integration tests ==="
        php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc -d plugins$FLYVEMDM_PATH/tests/suite-integration
        if [ "$2" == "-u" ]; then # Uninstalation process
            echo "=== Uninstall tests ==="
            php plugins$FLYVEMDM_PATH/vendor/bin/atoum --debug -bf plugins$FLYVEMDM_PATH/tests/bootstrap.php -ncc -d plugins$FLYVEMDM_PATH/tests/suite-uninstall
        fi
    fi
    cd -
else
    echo '
        Description: With this tool you can install the unit tests, execute all tests and execute an individual test

        Usage: flyvemdm-test -i -eall -u
               flyvemdm-test [options]
        Options:
            -i     Installing the tests.
                -eall  Execute all tests (Unit tests, Integration tests). This params is after of "-i".
                -eone  Execute one tests (Unit tests, Integration tests). This params is after of "-i".
                    $ After the param "-eone" you have to indicate the test to execute.
                    eg: flyvemdm-test -i -eone <source to test (File or directory)>
            -u     Uninstall all tests. You can use this parameter in the start or in the end
            -h     This help.'
fi