#ARGS
ARG MYSQL_TAG=${MYSQL_TAG}

FROM mysql:${MYSQL_TAG}

ARG MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
# MySql database parameters
ENV MYSQL_ROOT_PASSWORD ${MYSQL_ROOT_PASSWORD}
ENV MYSQL_DATABASE ${GLPI_DB_NAME}
